### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by Saplings-Projects** [Saplings-Projects/Birthday-2024#10]
Relatively simple screen with settings responsible for resolution and volume. Access to this menu should be possible from every other screen and it should return to the screen it was opened from. Can be done as a popup windows appearing in the middle of the screen but still showing previous scene closer to the display edges. Refer to https://discord.com/channels/877085190655205406/1162414864845783161/1181718743865376820 for screen design

**Comment by BishopJohnson** [comment]
Would we want the UI for the settings to have functionality implemented (e.g. selecting resolution resizes the screen) for this issue to be complete or is the UI simply existing and being navigable sufficient?
