### ISSUE TITLE
Missing Message Gallery emotes

### ISSUE THREAD

**Issue by Mikotey** [Saplings-Projects/Birthday-2024#101]
Some message submissions have emotes using different tokens than the ones expected.

Minimum: Add the missing tokens to the TokenEmoteDictionary or replace the emote tokens in the messages to their equivalent token

I think I recall there being at least 1 emote that was not a standard emote. I believe it was slapR which I presume is the slap emote but flipped horizontally. We should collect and decide what to do with those tokens.
Minimum: remove them or replace them with the closest emote
Potential: add those emotes to the game (might require making some additional art assets)

**Comment by Saplings-Projects** [comment]
I already went through all of them yesterday and went with replacement of those tags with the closest one
https://github.com/Saplings-Projects/Birthday-2024/tree/MessagesUpdate
Reversed slap is a modification of YT emote and in amend to the announcement we only talked about actual member emotes, so I went with replacement as well. Would that be okay with you?

Casulono
