### ISSUE TITLE
Duplicated message on last page

### ISSUE THREAD

**Issue by Casulono** [Saplings-Projects/Birthday-2024#115]
**Describe the bug**
The last page has a copy of the message from the first page or the second to the last page, depending on the direction we're going

**To Reproduce**
1. Go to Saplings Messages
2. Go to the last page of messages either by going back one page or through all other

**Expected behavior**
Last page should only have Zannmaster's message

**Screenshots**
![image](https://github.com/Saplings-Projects/Birthday-2024/assets/150629422/db93fd5f-35c1-42ee-9bdf-9b79d7a1e5b3)
![image](https://github.com/Saplings-Projects/Birthday-2024/assets/150629422/eafe42d8-0074-4d8c-ad46-b265bb2ff2d8)

**Comment by Mikotey** [comment]
I am guessing the issue is with not hiding remaining boxes.
So far, all the pages have been full, but the last page now only has 1 message and is incomplete.

The adjustment needed is probably hiding extra boxes until explicitly needed
