### ISSUE TITLE
Edit button in saplings level is still accessible

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/Birthday-2024#128]
**Describe the bug**
As the title says. This allows seeing the solution also.

**To Reproduce**
1. Select any sapling level (not the campaign one)
2. Click on the edit button on the bottom left
3. You can now see the solution, export, import, etc...

**Expected behavior**
You shouldn't be able to edit a sapling submitted level, the button should not be there.

**Screenshots**
![gscreenshot_2024-03-17-194711](https://github.com/Saplings-Projects/Birthday-2024/assets/49365680/ad51143a-fe6d-432f-9762-1d4f7fccf276)
![gscreenshot_2024-03-17-194714](https://github.com/Saplings-Projects/Birthday-2024/assets/49365680/ef2b2924-f540-4d32-84f3-3ee14fca7bf9)

**Environment**
 - Linux X11, on commit 8bc6a21998df311fc892dadb09cd09001f56a8ab

**Comment by Mikotey** [comment]
This is included in this issue: https://github.com/Saplings-Projects/Birthday-2024/issues/93

**Comment by Turtyo** [comment]
Guess we should a duplicate tag and close this one then

**Comment by Casulono** [comment]
Duplicate of: https://github.com/Saplings-Projects/Birthday-2024/issues/93
