### ISSUE TITLE
BUG (low) - Photo taken before grid is updated

### ISSUE THREAD

**Issue by Mikotey** [Saplings-Projects/Birthday-2024#141]
![image](https://github.com/Saplings-Projects/Birthday-2024/assets/9286524/4b557b22-0679-4fd8-9223-adfa2b75c4e1)

When the last piece is placed to complete a level, the screen capture occurs before the grid is updated visually.
This causes some of the squares to not be gold in the photograph image

**Comment by Mikotey** [comment]
Should be fixed with a brief wait before taking the screen capture.
Something like "await 0.05 seconds"

**Comment by Casulono** [comment]
oh, didn't notice this issue, I have a fix for this in recent PR
