### ISSUE TITLE
REQUEST: Remove the discord server mention from the splash

### ISSUE THREAD

**Issue by Mikotey** [Saplings-Projects/Birthday-2024#154]
Murphy requests that we remove the server discord mention from the splash screen, and proposes that it be moved to the Credits screen instead

**Comment by Mikotey** [comment]
Note: if approved, make sure to take another screenshot of the splash screen without the "Press to Continue" and replace the SpoofedSplash image

**Comment by Casulono** [comment]
currently working on this together with rewording of copyrights and other splash screen/credits related requests

**Comment by Mikotey** [comment]
I approved it, but didn't look at it proper. The community text seems a little small. I would think to make it at least as big as the copyright. Also, above the copyright, I think. Like swap places
