### ISSUE TITLE
Resolution changing in settings

### ISSUE THREAD

**Issue by Saplings-Projects** [Saplings-Projects/Birthday-2024#18]
Assets are created for 1920x1080p. We need code for proper scalony of UI assets to other screen sizes

**Comment by Mikotey** [comment]
By trying to get things to scale properly, I've unintentionally been working on this task anyway

**Comment by Mikotey** [comment]
Updating the project display settings and adjusting the UI transforms should be enough to accommodate other aspect ratios and resolutions

**Comment by Mikotey** [comment]
So in terms of project settings, this should be done. Things will need to be adjusted to have proper anchorings, but that will be per case such as with task https://github.com/Saplings-Projects/Birthday-2024/issues/23
