### ISSUE TITLE
Level Select screen - Select level

### ISSUE THREAD

**Issue by Mikotey** [Saplings-Projects/Birthday-2024#2]
Setup a scene that populates using the LevelSetup resources (example: "TestLevel.tres"). Doesn't have to be dynamic

Selecting a level should load the main_level.tscn and pass the selected LevelSetup data to the GridLogic.LoadLevel()

**Comment by Mikotey** [comment]
Feel free to make more test levels so there are more to select for testing

**Comment by Casulono** [comment]
taking this one; I'll be able to work a bit during Christmas
