### ISSUE TITLE
Pieces in game screen should not be interctable with settings wondow opened

### ISSUE THREAD

**Issue by Casulono** [Saplings-Projects/Birthday-2024#24]
From https://github.com/Saplings-Projects/Birthday-2024/pull/19
Self-explanatory title

**Comment by Mikotey** [comment]
Have an idea of adding some APIs to the ScreenManager to ask it what the current/top-level screen is. If it's not the main level, meaning settings/victory/popup is over it, don't manipulate piece

**Comment by Mikotey** [comment]
already applied the fix to the editor fork. Just need to copy it over
