### ISSUE TITLE
Level scene should go back to level select menu

### ISSUE THREAD

**Issue by Saplings-Projects** [Saplings-Projects/Birthday-2024#27]
Currently "Back" button on main_level leads to main_menu. It should guide player to the level_select of the campaign that was chosen

**Comment by Mikotey** [comment]
I'm including the level navigations of "skip" and "next" in the level scene into this. However, that relies on the progression manager of issue https://github.com/Saplings-Projects/Birthday-2024/issues/62 , so I will be working on that first
