### ISSUE TITLE
Level with no pieces is valid and can be created

### ISSUE THREAD

**Issue by Casulono** [Saplings-Projects/Birthday-2024#38]
**Describe the bug**
A level with no pieces is still counted as valid

**To Reproduce**
1. Open editor
2. Remove all pieces
3. Play

**Expected behavior**
Warning and prevention of creating a level not possible to complete/without any pieces

**Additional context**
No pieces to place = no way of achieving win state

**Comment by Mikotey** [comment]
This doesn't cause instability or put the player in a locked state, so should be fine to ignore. I don't think the player should be able to win with an empty level, and it sort of enforces having to add at least 1 piece that way. The player can still navigate away from the editor page or go back to editor mode safely
