### ISSUE TITLE
SFX and other noise samples have background noises

### ISSUE THREAD

**Issue by Casulono** [Saplings-Projects/Birthday-2024#39]
As in the title. Some sounds have background noises from streams like music from the game Fauna played at the moment. We need to clean those samples to leave only Fauna noises or find new ones that would be cleaner.

**Comment by Casulono** [comment]
linked with #15

**Comment by Mikotey** [comment]
One tool I found really useful for isolating vocals was this application with Demucs: https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v5.6

You can get the installer from the download link in the readme or here: https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.6/UVR_v5.6.0_setup.exe

![image](https://github.com/Saplings-Projects/Birthday-2024/assets/9286524/076fc42f-6fcd-4272-be27-e959a1455536)
Set the process method to Demucs, the stem to Vocals, and check GPU conversion. Setup the file input & output paths and click "start processing". It's a very nice and simple tool

**Comment by Casulono** [comment]
Have you also done some tests and compared sample before and after?
