### ISSUE TITLE
Prompt with controls

### ISSUE THREAD

**Issue by Casulono** [Saplings-Projects/Birthday-2024#40]
Self-explanatory, we need a popup or text with controls. They are simple but they are not stated anywhere

**Comment by Casulono** [comment]
Controls are now on main level screen: ![image](https://github.com/Saplings-Projects/Birthday-2024/assets/150629422/09c04629-4693-4846-9203-b24a699af019)

**Comment by Mikotey** [comment]
I have an idea using the popup system to show a prompt to the player on level start. We can use that to introduce controls and new pieces
