### ISSUE TITLE
Make pieces gallery more inline with other menus

### ISSUE THREAD

**Issue by Casulono** [Saplings-Projects/Birthday-2024#81]
Currently pieces gallery is one scene with no animations. Level selections screens that use the same layout are split to separate screens with proper transitions. Issue is for making pieces gallery use page turning animation. If split is needed then it is also part of this issue.

**Comment by Mikotey** [comment]
I can try to make the transition animation be invokable outside of a scene transition so it doesn't have to be split up into a bunch of scenes

**Comment by Mikotey** [comment]
Just need to apply the transition changes made for Message Gallery
