### ISSUE TITLE
Level editor changes

### ISSUE THREAD

**Issue by Casulono** [Saplings-Projects/Birthday-2024#93]
The level editor in its current form shouldn't be accessible as it can serve as a way to break puzzles. The proposed solution is to have it accessible from the main menu and it would lead to the blank level for import and export. Importing level should change scene directly to the playable level to not spoil the solution of the puzzle but clicking "Edit" should allow to change puzzle as usual

**Comment by Mikotey** [comment]
Minimum: Hide the Editor button

Potential: Have the Editor accessible via the Main Menu with the features described above
