### ISSUE TITLE
Campaign Tutorial text prompts review

### ISSUE THREAD

**Issue by Mikotey** [Saplings-Projects/Birthday-2024#95]
It would be good to go through the Campaign tutorial prompts and double check for grammar

**Comment by Casulono** [comment]
Source: https://docs.google.com/document/d/1S3WOWa9PXuciC7sfY3kF3A0drbg6zLhRgSIVoDHJR6U/edit

**Comment by Mikotey** [comment]
Went through the document and added my recommended changes and suggestions
